language: cpp
compiler:
  - clang
before_install:
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo apt-get update
  - sudo apt-get install -f libboost1.49-dev libboost-serialization1.49-dev libboost-filesystem1.49-dev libboost-system1.49-dev libboost-test1.49-dev libboost-thread1.49-dev
before_script:
  - git submodule update --init --recursive
  - cd test
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
script:
  - ./waf configure install
  - ./bin/main

# vim: et ts=2 sw=2
